# This is a basic workflow to help you get started with Actions

name: Integration Continue

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Construction du package
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Là je vais construire le package
          echo test, and deploy your project.
          echo "Coucou tout le monde Où je me trouve (pwd)"
          pwd
          echo "Contenu du repository que j'ai récupéré dans $GITHUB_WORKSPACE"
          ls -l $GITHUB_WORKSPACE
          date
          
  test_uni:
    # The type of runner that the job will run on
    name: Tests unitaires
    needs: build
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          date
          echo coucou je modifie le libellé du test unitaire
          echo Visualisation OK ?
          
        run: |
          date
          echo Re coucou j'ajoute une action au test
          echo Modification prise compte ?  
  deploy:
    # The type of runner that the job will run on
    name: Deploiement des packages sur REC
    needs: test_uni
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          date
          echo Etape de deploiement

  test_reg:
    # The type of runner that the job will run on
    name: Tests non reg sur REC
    needs: deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          date
          echo LA NOUS ALLONS METTRE LES TESTS
          ls -l ${{ github.workspace }}/src
          chmod -R 777 ${{ github.workspace }}
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/src
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/resultat
